version: '2.3'
services:
  tfgpu:
    container_name: 'container_tfgpu'
    build: ./img_tfgpu
    image: img_tfgpu 
    #bien mettre image apres le build, pour renommer l'image ainsi built
    ports:
      - 8888:8888
    volumes:
      - ~/git/coding:/tf/coding
    runtime: nvidia
    command: tail -F anything
    #the tail command will wait forever for the file anything to appear
